publicHoistPattern:
  - "@rspack/core"
packages:
  - "packages/@tats-u/docusaurus-plugin-copy-temml-assets"
overrides:
  compression@1.8.0>on-headers: 1.1.0
minimumReleaseAge: 1440
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200
blockExoticSubdeps: true
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@swc/core"
  - core-js
  - core-js-pure
  - esbuild
