name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Build packages
        run: node --run build
        working-directory: packages/@tats-u/docusaurus-plugin-copy-katex-assets
      - run: pnpm publish --provenance --access public --no-git-checks
        working-directory: packages/@tats-u/docusaurus-plugin-copy-katex-assets
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
